---
- name: Install prerequisties
  hosts: all
  gather_facts: false
  become: true
  tasks:
    # - name: Wait 200 seconds for port 22 to become open and contain "OpenSSH"
    #   wait_for:
    #     port: 22
    #     host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
    #     search_regex: OpenSSH
    #     delay: 10
    #     timeout: 200
    #   vars:
    #     ansible_connection: local

    - name: Set a hostname
      hostname:
        name: "{{ node_hostname }}"

    - name: Install necassary packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - vim
          - net-tools

    - name: add docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu noble stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install containerd.io
      apt:
        pkg:
          - containerd.io

    - name: Enable containerd
      systemd:
        name: containerd
        daemon_reload: yes
        state: started
        enabled: yes

    - name: Setup containerd to use systemd as cgroup
      copy:
        backup: true
        src: ./files/containerd-config.toml
        dest: /etc/containerd/config.toml

    - name: Restart service cron, in all cases, also issue daemon-reload to pick up config changes
      systemd:
        state: restarted
        daemon_reload: yes
        name: containerd

- name: Setup Outline Server
  hosts: server
  become: true
  tasks:
    - name: install outline server
      shell: sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)" --keys-port=443 --api-port=8080

    - name: Copy outline access.txt locally
      fetch:
        src: /opt/outline/access.txt
        dest: ./files/access.txt
        flat: yes

